FROM ballerina/ballerina:2201.10.1

USER root

WORKDIR /app

RUN mkdir -p /app && chomod -R 777 /app

COPY . .

RUN mkdir -p /app/target && chmod -R 777 /app/target && bal build

EXPOSE 8080 9092

CMD ["bal", "run"]